export const plans = [
	{
		"planid":1,
		"plantype":"FREE",
		"storage":"500MB",
		"share_files":false,
		"price":0,
		"support":false,
		"period":""
	},
	{
		"planid":2,
		"plantype":"STANDARD",
		"storage":"1GB",
		"share_files":true,
		"price":500,
		"support":true,
		"period":""
	},	
	{
		"planid":3,
		"plantype":"PREMIUM",
		"storage":"2GB",
		"share_files":true,
		"price":1000,
		"support":true,
		"period":""
	},	
	{
		"planid":4,
		"plantype":"ENTERPRISE",
		"storage":"1TB",
		"share_files":true,
		"price":5000,
		"period":"",
		"support":true
	}
]

